# Generated by grenade-mac/scripts/cask.sh at each release. Change that script, not this file.
# It belongs in the tap as Casks/grenade-app.rb: brew install --cask holdgrenade/tap/grenade-app
cask "grenade-app" do
  version "1.0.169"
  sha256 "e3be3767bdab632d75d41223b32eb9938aad539f563a91f94e7078930466896a"

  url "https://downloads.holdgrenade.com/mac/Grenade-#{version}.dmg"
  name "Grenade"
  desc "Watch and drive the AI coding agents in your terminals, beside them"
  homepage "https://www.holdgrenade.com/"

  livecheck do
    url "https://downloads.holdgrenade.com/mac/latest.json"
    regex(/"version"\s*:\s*"(\d+(?:\.\d+)+)"/i)
  end

  auto_updates true
  depends_on macos: :tahoe

  app "Grenade.app"

  zap trash: [
    "~/Library/Application Support/Grenade",
    "~/Library/Caches/com.holdgrenade.grenade.mac",
    "~/Library/HTTPStorages/com.holdgrenade.grenade.mac",
    "~/Library/Preferences/com.holdgrenade.grenade.mac.plist",
    "~/Library/Saved Application State/com.holdgrenade.grenade.mac.savedState",
  ]
end
