# Generated by grenade-backend/scripts/release.mjs. Change packaging/homebrew/formula.mjs, not this file.
# It belongs in the tap as Formula/grenade.rb: brew install holdgrenade/tap/grenade
class Grenade < Formula
  desc "Watch and drive AI coding agents in your Mac's terminals from your phone"
  homepage "https://github.com/holdgrenade/grenade-backend"
  url "https://github.com/holdgrenade/grenade-backend/releases/download/v0.1.0/grenade-remote-0.1.0.tgz"
  sha256 "dba4cb36a50d8b26658ee37cb30c6cdada57b8cc09181c5155b24b078beae115"
  license "MIT"

  depends_on :macos
  depends_on "node"
  depends_on "tmux"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink libexec.glob("bin/*")
  end

  def caveats
    <<~EOS
      Set Grenade up and pair your phone:
        grenade setup
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/grenade --version")
  end
end
