# Generated by grenade-cli/scripts/release.mjs. Change packaging/homebrew/formula.mjs, not this file.
# It belongs in the tap as Formula/grenade.rb: brew install holdgrenade/tap/grenade
class Grenade < Formula
  desc "Watch and drive AI coding agents in your Mac's terminals from your phone"
  homepage "https://github.com/holdgrenade/grenade-cli"
  url "https://github.com/holdgrenade/grenade-cli/releases/download/v0.1.10/holdgrenade-cli-0.1.10.tgz"
  sha256 "47ea4b6ee177542d890ba57453b2754d99ebd4f1d59869b88d7a6133b0ac2b29"
  license "MIT"

  depends_on :macos
  depends_on "node"
  depends_on "tmux"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink libexec.glob("bin/*")
  end

  def caveats
    <<~EOS
      Set Grenade up and pair your phone:
        grenade setup
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/grenade --version")
  end
end
