# Generated by grenade-cli/scripts/release.mjs. Change packaging/homebrew/formula.mjs, not this file.
# It belongs in the tap as Formula/grenade.rb: brew install holdgrenade/tap/grenade
class Grenade < Formula
  desc "Watch and drive AI coding agents in your Mac's terminals from your phone"
  homepage "https://www.holdgrenade.com"
  url "https://github.com/holdgrenade/grenade-cli/releases/download/v1.0.82/holdgrenade-cli-1.0.82.tgz"
  sha256 "65b1d57a41aef906c90beafe33f7e673fa82109488eff31ce3a8cc2e4a020b54"
  license "MIT"

  depends_on :macos
  depends_on "node"
  depends_on "tmux"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink libexec.glob("bin/*")
  end

  def caveats
    <<~EOS
      Set Grenade up and pair your phone:
        grenade setup
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/grenade --version")
  end
end
